SELECT 
    *
FROM
    customer_shopping_behaviour;

-- Q1. What is the total revenue generated by male vs female customers

SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer_shopping_behaviour
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount

SELECT AGE
    customer_id, purchase_amount
FROM
    customer_shopping_behaviour
WHERE
    discount_applied = 'Yes'
        AND purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customer_shopping_behaviour);

-- Q3. Which are the top 5 products with the highest average review rating 

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'Average_Product_rating'
FROM
    customer_shopping_behaviour
GROUP BY item_purchased
ORDER BY Average_Product_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS 'Average_spending'
FROM
    customer_shopping_behaviour
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more ? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_cutomers,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM
    customer_shopping_behaviour
GROUP BY subscription_status;

 
-- Q6. Which 5 products have the highest percentage of purchases with discount applied

SELECT item_purchased , CONCAT(ROUND(AVG(purchase_amount),2),'%') AS highest_revenue_products FROM customer_shopping_behaviour
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY highest_revenue_products DESC
LIMIT 5;


SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_shopping_behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New , Returning, and Loyal based on their total number of previous purchases, and show the count of each segment

 with customer_type AS (
 SELECT customer_id, previous_purchases,
 CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
FROM customer_shopping_behaviour
)

SELECT customer_segment , COUNT(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased product with each category

WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() over(partition by category  order by COUNT(customer_id) DESC) AS item_rank
FROM customer_shopping_behaviour
GROUP BY category, item_purchased
)

SELECT item_rank, category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT subscription_status , COUNT(customer_id) AS repeat_buyers 
FROM customer_shopping_behaviour
WHERE previous_purchases > 5;

-- Q10. What is the revenue contribution of each age group

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC

    